# Find individuals with difference between birth date in birth certificate and the date in the reconstruction.

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX pico: <https://personsincontext.org/model#>
PREFIX sdo: <https://schema.org/>

select ?pr ?pr_death_date ?po_death_date where {
	?pr sdo:deathDate ?pr_death_date ;
        prov:wasDerivedFrom ?bn_po .

    ?bn_po prov:hadPrimarySource/owl:sameAs ?source .

    ?source sdo:additionalType <https://terms.personsincontext.org/553> .
    
    ?po prov:hadPrimarySource ?source ;
    	sdo:deathDate ?po_death_date .
  
    FILTER(?pr_death_date != ?po_death_date)
} 